---
branches:
  except:
  - gh-pages

language: node_js
node_js:
  - node
  - lts/*
cache:
  directories:
    - ~/.npm
    - .jest
before_script:
  # - cd react-native-multi-platform
  - make install
  - make build
script:
  - make tests
jobs:
  include:
    - stage: deploy
      node_js: lts/*
      script:
        - make publish-expo
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: react-native-multi-platform/build
  on:
    branch: feature/#3-gh-pages
